apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: bmbapp-eks
  region: ap-south-1

nodeGroups:
  - name: ng1
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName:  bmbeks
  - name: ng2
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:
      publicKeyName:  bmbeks
